### ISSUE TITLE
can't save files with special characters

### ISSUE THREAD

**Issue by pablodav** [flathub/org.openshot.OpenShot#2]
If I try to save some file in /home/user/Vídeos it doesn't works as it gives me error with invalid characters.

Same thing happens if I try to use some special character in the name of the file, like energy in spanish: Energía.

same thing happens if I try to import files from "Images" folder in spanish: Imágenes:

```
 main_window:INFO Imported media file /home/pablo/Im\xe1genes/Captura de pantalla de 2018-09-15 17-23-39.png
files_listview:INFO updateSelection
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/openshot_qt/windows/main_window.py", line 590, in actionImportFiles_trigger
    if not recommended_path or not os.path.exists(recommended_path):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 14: ordinal not in range(128)
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *exception-successfully-sent*
files_listview:INFO updateSelection
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/openshot_qt/windows/main_window.py", line 590, in actionImportFiles_trigger
    if not recommended_path or not os.path.exists(recommended_path):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 14: ordinal not in range(128)
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ | *duplicate-exception-ignored*
```

**Comment by eszlari** [comment]
Should be fixed: https://github.com/flathub/org.openshot.OpenShot/commit/7a0280ae189f58a7c63ed1a46fc1ab7c9f686c6e

Please try it, when the build is finished: https://flathub.org/builds/#/builders/2/builds/4733

**Comment by eszlari** [comment]
@pablodav Can you confirm that it works for you now?

**Comment by pablodav** [comment]
Didn't test it again, but will reopen the issue if it still happens.

Thanks.
